{{- if .Values.backend.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tabularasa.pvcName" . }}
  labels:
    {{- include "tabularasa.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | quote }}
  {{- with .Values.backend.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end -}}
