apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tabularasa.secretName" . }}
  labels:
    {{- include "tabularasa.labels" . | nindent 4 }}
type: Opaque
stringData:
  GOMAPROXY_ENCRYPTION_KEY: {{ .Values.backend.secrets.encryptionKey | quote }}
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.backend.secrets.googleClientId | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.backend.secrets.googleClientSecret | quote }}
