apiVersion: v1
kind: Service
metadata:
  name: {{ include "tabularasa.fullname" . }}
  labels:
    {{- include "tabularasa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "tabularasa.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.frontendPort }}
      targetPort: frontend
      protocol: TCP
    - name: api
      port: {{ .Values.service.backendPort }}
      targetPort: backend
      protocol: TCP
